[build]
  publish = "."
  functions = "netlify/functions"

[[redirects]]
  from = "/week1"
  to   = "/week1/index.html"
  status = 200

[[redirects]]
  from = "/week2"
  to   = "/week2/index.html"
  status = 200

[[redirects]]
  from = "/week3"
  to   = "/week3/index.html"
  status = 200

[[redirects]]
  from = "/week4"
  to   = "/week4/index.html"
  status = 200

[[redirects]]
  from = "/week5"
  to   = "/week5/index.html"
  status = 200

[[redirects]]
  from = "/week6"
  to   = "/week6/index.html"
  status = 200

[[redirects]]
  from = "/week7"
  to   = "/week7/index.html"
  status = 200

[[redirects]]
  from = "/week8"
  to   = "/week8/index.html"
  status = 200

[[redirects]]
  from = "/week9"
  to   = "/week9/index.html"
  status = 200

[[redirects]]
  from = "/week10"
  to   = "/week10/index.html"
  status = 200
